name: news_explorer_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^3.0.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  intl: ^0.20.2
  share_plus: ^12.0.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  mockito: ^5.4.4
  hive_test: ^1.0.1
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4


flutter:

  uses-material-design: true

  assets:
     - .env


